// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "THIS IS CHANGED, CHANGE IT TO YOURS;

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onWaterOn1Change();
void onWaterOn2Change();

int soil_Dryness_1;
int soil_Dryness_2;
bool float_Sensor;
bool water_On_1;
bool water_On_2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(soil_Dryness_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_Dryness_2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(float_Sensor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(water_On_1, READWRITE, ON_CHANGE, onWaterOn1Change);
  ArduinoCloud.addProperty(water_On_2, READWRITE, ON_CHANGE, onWaterOn2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
